
version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: delete older package-lock-json Dependencies
          command: rm -rf package-lock.json node_modules 
      - run:
          name: Setup Dependencies
          command: npm install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run: # run tests
          name: Run Test 
          command: |
            npm test          
orbs:
  cypress: cypress-io/cypress@1

workflows:         
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
      - cypress/run # "run" job comes from "cypress" orb


