
version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: delete older package-lock-json Dependencies
          command: rm -rf package-lock.json node_modules 
      - run:
          name: Setup Dependencies
          command: npm install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

  # example test job with 2 commands
  # 1. starts the app in the background
  # 2. runs the tests in a separate command
  two-commands:
    docker:
      # find Docker image at https://github.com/cypress-io/cypress-docker-images
      - image: cypress/base:12.12.0

    working_directory: ~/repo

    steps:
      - checkout
      - restore-cached-dependencies
      - install-dependencies
      - cache-dependencies

      - run:
          name: Start TodoMVC server
          command: npm start
          working_directory: todomvc
          background: true

      - run:
          name: Run Cypress tests
          command: npm test
